### ISSUE TITLE
EDEPRECATED_MODULE

### ISSUE THREAD

**Issue by dongri** [Amovane/aptos-NFT-marketplace#1]
list_token_for_swap, exchange_coin_for_token are now deprecated

https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-token/sources/token_coin_swap.move#L103-L114

**Comment by Lastferbbs** [comment]
Work around for now would be taking token_coin_swap before deprecation and publishing it by yourself

**Comment by laviosa08** [comment]
Since its deprecated what will be the new way to list the token for swap?
